### ISSUE TITLE
退会できない

### ISSUE THREAD

**Issue by deerboy** [camp-team/MusiL#101]
![image](https://user-images.githubusercontent.com/5842851/91687138-07687a80-eb9a-11ea-983e-8cde12d0563c.png)

**Comment by komura-c** [comment]
こちら、Cloud Functionsの環境変数のtokenを間違えていた問題でした。
修正いたしましたのでクローズさせていただきます。

**Comment by komura-c** [comment]
<img width="579" alt="delete" src="https://user-images.githubusercontent.com/37304826/91729494-98ae1000-ebdf-11ea-883f-dd7ab3002922.png">
