### ISSUE TITLE
本来見せちゃいけない記事を見せないような権限にする

### ISSUE THREAD

**Issue by deerboy** [camp-team/MusiL#108]
非公開の記事が誰でもダウンロードできてしまうのでルールを改善

**Comment by komura-c** [comment]
前回のPRにて記述を忘れてしまっていましたが、こちらにて修正しました。
重要な変更のため、お手数ですがご確認お願いいたします。
[fix(firestore): rulesを一旦修正](https://github.com/camp-team/MusiL/pull/116/commits/d32b184603b03247a740a0d08c86cf497a324d66)

**Comment by deerboy** [comment]
👍

**Comment by komura-c** [comment]
ありがとうございます！クローズします！
