### ISSUE TITLE
TwitterプロフィールのURLバグ修正

### ISSUE THREAD

**Issue by deerboy** [camp-team/MusiL#94]
![image](https://user-images.githubusercontent.com/5842851/91686747-1995e900-eb99-11ea-8a28-23eb60aad24a.png)

**Comment by komura-c** [comment]
僕や他の方のは正しく表示されたため、Twitter側のバグかと思われます！
紛らわしい処理を記述していてすみません…
クローズします！
![image](https://user-images.githubusercontent.com/37304826/91922252-77950e80-ed08-11ea-9fca-64d4cf612012.png)
