### ISSUE TITLE
Twitter Cardチェック

### ISSUE THREAD

**Issue by deerboy** [camp-team/MusiL#95]
![image](https://user-images.githubusercontent.com/5842851/91686826-4c3fe180-eb99-11ea-9611-0980bd408f20.png)

**Comment by komura-c** [comment]
#113 の functionsにhtmlToTextを導入、テキストに置換 にて修正いたしましたのでクローズさせていただきます。
![image](https://user-images.githubusercontent.com/37304826/92196713-d1cdd500-eeaa-11ea-9187-dfeb82394924.png)
